FROM openjdk:8-jdk-alpine

# Install Maven
RUN apk add --no-cache maven

# Copy the project files
COPY . /usr/src/app

# Set the working directory
WORKDIR /usr/src/app

# Build the application
RUN mvn clean package

# Expose the port the app runs on
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "target/sample-0.0.1-SNAPSHOT.jar"]